# Generated by Django 4.0.2 on 2022-02-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('qty', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('productinsurance', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('img1', models.ImageField(blank=True, upload_to='img_produce')),
                ('img2', models.ImageField(blank=True, upload_to='img_produce')),
                ('img3', models.ImageField(blank=True, upload_to='img_produce')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('nname', models.CharField(max_length=50)),
                ('sex', models.IntegerField()),
                ('tell', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=255)),
                ('status_u', models.IntegerField(default=2)),
                ('images', models.ImageField(blank=True, upload_to='img_users')),
            ],
        ),
    ]
